apiVersion: v1
kind: Service
metadata:
  name: helloworld-backend-service #name of the service, must be DNS compliant
  labels:
    service: helloWorld-backend #label in the service
spec:
  ports:
    - port: 5002
  selector:
    app: HelloWorld
    tier: backend
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-backend #name on the pods, must be DNS compliant
  labels:
    app: HelloWorld #label on the Deployment/workload - all the podes
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: HelloWorld
      tier: backend 
  template:
    metadata:
      labels:
        app: HelloWorld #label on the Deployment/workload - all the podes
        tier: backend
    spec:
      containers:
      - image: us.gcr.io/exemplary-tide-208514/helloworld-backend-image:latest
        name: backend-service #name on the container in the pod, must be DNS compliant
        ports:
            - containerPort: 5002 #port exposed on the container's host